FROM node:20-alpine

WORKDIR /usr/app

COPY package.json ./

RUN npm install

COPY . .

ARG DATABASE_HOST

ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_PORT=$DATABASE_PORT
ENV JWT_SECRET=$JWT_SECRET

RUN echo "DATABASE_HOST=${DATABASE_HOST}" > .env
RUN echo "DATABASE_USER=${DATABASE_USER}" > .env
RUN echo "DATABASE_NAME=${DATABASE_NAME}" > .env
RUN echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" > .env
RUN echo "DATABASE_PORT=${DATABASE_PORT}" > .env
RUN echo "JWT_SECRET=${JWT_SECRET}" > .env

RUN npm i -g pnpm

RUN pnpm build

EXPOSE 3000

CMD ["node", "build/app"]